# Generated by Django 2.0 on 2018-10-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action_type', models.CharField(max_length=6)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='icons/events/')),
                ('start_time', models.IntegerField()),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('success_message', models.TextField()),
                ('failure_message', models.TextField()),
                ('end_time', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.ChatSession')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('token', models.CharField(max_length=40, unique=True)),
                ('chat_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.ChatSession')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.FileField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDepot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceEventState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('deployed', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.FileField(upload_to='icons/roles/')),
                ('resources', models.ManyToManyField(through='neo_api.ResourceDepot', to='neo_api.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('events', models.ManyToManyField(to='neo_api.Event')),
                ('roles', models.ManyToManyField(to='neo_api.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('proctorNotes', models.TextField(default='')),
                ('sessionNotes', models.TextField(default='')),
                ('scenario_ran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('enforce_order', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Resource')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='resourceeventstate',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Role'),
        ),
        migrations.AddField(
            model_name='resourceeventstate',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neo_api.Session'),
        ),
        migrations.AddField(
            model_name='resourcedepot',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Role'),
        ),
        migrations.AddField(
            model_name='participant',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.Role'),
        ),
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neo_api.Score'),
        ),
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.Session'),
        ),
        migrations.AddField(
            model_name='message',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='success_resources',
            field=models.ManyToManyField(through='neo_api.Threshold', to='neo_api.Resource'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.Session'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Role'),
        ),
        migrations.AddField(
            model_name='briefing',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Scenario'),
        ),
        migrations.AddField(
            model_name='action',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.Event'),
        ),
        migrations.AddField(
            model_name='action',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.Participant'),
        ),
        migrations.AddField(
            model_name='action',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.Resource'),
        ),
        migrations.AddField(
            model_name='action',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Session'),
        ),
    ]
