# Generated by Django 2.0 on 2018-03-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threshold',
            old_name='role',
            new_name='resource',
        ),
        migrations.AlterField(
            model_name='participant',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Score'),
        ),
    ]
