# Generated by Django 2.0 on 2018-04-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceEventState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('deployed', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neo_api.Resource')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neo_api.Session')),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='resource',
        ),
        migrations.AddField(
            model_name='action',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.Resource'),
        ),
    ]
