# Generated by Django 2.0 on 2018-02-14 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='star_time',
            new_name='start_time',
        ),
    ]
