# Generated by Django 2.0 on 2018-04-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0002_auto_20180406_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sessionKey',
            field=models.CharField(default='test', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
