# Generated by Django 2.0 on 2018-04-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0003_session_sessionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='participant',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='resourceeventstate',
            name='deployed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resourceeventstate',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
