# Generated by Django 2.0 on 2018-06-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0005_chatsession_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.AddField(
            model_name='participant',
            name='chat_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neo_api.ChatSession'),
        ),
    ]
