# Generated by Django 2.0 on 2018-06-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0006_auto_20180629_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neo_api.ChatSession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neo_api.Participant'),
            preserve_default=False,
        ),
    ]
