# Generated by Django 2.0 on 2018-07-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0007_auto_20180629_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='title',
            field=models.TextField(default=8),
            preserve_default=False,
        ),
    ]
