# Generated by Django 2.0 on 2018-10-12 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0012_auto_20180830_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
