# Generated by Django 2.0 on 2018-10-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo_api', '0013_session_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.IntegerField(default=10),
        ),
    ]
